queue_rules:
  - name: default
    conditions:
      - check-success=ci

pull_request_rules:
  - name: Auto Squash and Merge
    conditions:
      - base=master
      - status-success=ci
      - 'label=ready to squash and merge'
    actions:
      delete_head_branch: {}
      queue:
        method: squash
        name: default
  - name: Auto Rebase and Merge
    conditions:
      - base=master
      - status-success=ci
      - 'label=ready to rebase and merge'
    actions:
      delete_head_branch: {}
      queue:
        method: rebase
        name: default
