name: 'CI'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    needs: [test, downstream]
    runs-on: ubuntu-latest
    steps:
      - run: true
  test:
    name: yarn ${{ matrix.yarncmd }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yarncmd: ['test', 'docs']
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --pure-lockfile
      - name: Run Tests
        run: yarn ${{ matrix.yarncmd }}

  downstream:
    name: Test downstream ${{ matrix.group }} projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: ['angular', 'angularjs', 'react', 'other']
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to Test Downstream Projects
        run: |
          npm config set scripts-prepend-node-path auto
          git config --global user.email uirouter@github.actions
          git config --global user.name uirouter_github_actions
      - name: Install Dependencies
        run: yarn install --pure-lockfile
      - name: Test Downstream Projects
        run: yarn test:downstream --group ${{ matrix.group }}
