on: [push]

jobs:
  yarn_upgrade:
    runs-on: ubuntu-latest
    name: Upgrade dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade devDependencies --latest
        id: upgrade
        uses: ui-router/publish-scripts/actions/upgrade@github-action-yarn-upgrade
        with:
          deptype: devDependencies
          exclude: ''
          latest: true
      # Use the output from the `hello` step
      # Do the pull request
      - name: List upgrades
        run: echo "Upgrades ${{ steps.upgrade.outputs.upgrades }}"
      - name: Create Pull Request
        if: ${{ steps.upgrade.outputs.upgrades != '' }}
        # https://github.com/peter-evans/create-pull-request/releases/tag/v2.7.0
        uses: peter-evans/create-pull-request@340e629d2f63059fb3e3f15437e92cfbc7acd85b
        with:
          commit-message: 'chore(package): Update to ${{ steps.upgrade.outputs.upgrades }}'
          title: 'chore(package): Update to ${{ steps.upgrade.outputs.upgrades }}'
